### Set your token here
@token = 10|bpmL3rvny7AsjRqOlVdzijX9Hm6ickpoaFv5T5tx701c902b
@base = http://127.0.0.1:8000/api

### Customers
GET {{base}}/customers
Authorization: Bearer {{token}}

### Products
GET {{base}}/products?q=&page=1&per_page=10
Authorization: Bearer {{token}}

### Employees
GET {{base}}/employees?page=1
Authorization: Bearer {{token}}

### Vendors
GET {{base}}/vendors?page=1
Authorization: Bearer {{token}}

### Roles
GET {{base}}/roles
Authorization: Bearer {{token}}

### Taxes
GET {{base}}/taxes
Authorization: Bearer {{token}}

### Payment Methods
GET {{base}}/payment-methods
Authorization: Bearer {{token}}

### Payments
GET {{base}}/payments?page=1
Authorization: Bearer {{token}}

### Receipts
GET {{base}}/receipts?page=1
Authorization: Bearer {{token}}

### Invoice Types
GET {{base}}/invoice-types
Authorization: Bearer {{token}}
