server {
    listen      149.50.143.129:8080;
    server_name pos.artdent.com.ar www.pos.artdent.com.ar;
    root        /home/artdent/web/pos.artdent.com.ar/public_html;
    index       index.html;

    access_log  /var/log/apache2/domains/pos.artdent.com.ar.log combined;
    error_log   /var/log/apache2/domains/pos.artdent.com.ar.error.log error;

    # Archivos estáticos
    location ~* \.(jpg|jpeg|gif|png|svg|webp|css|js|map|ico|woff2?|ttf|eot)$ {
        expires 7d; access_log off;
        try_files $uri =404;
    }

    # Fallback SPA (history API)
    location / {
        try_files $uri /index.html;
    }

    client_max_body_size 16m;
    include /home/artdent/conf/web/pos.artdent.com.ar/nginx.forcessl.conf*;
}
